// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Camera.proto

package sss.Camera;

public interface CameraResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sss.CameraResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes frame = 1;</code>
   */
  com.google.protobuf.ByteString getFrame();
}
