// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Camera.proto

package sss.Camera;

public final class CameraImpl {
  private CameraImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sss_CameraRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sss_CameraRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sss_CameraResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sss_CameraResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Camera.proto\022\003sss\"\037\n\rCameraRequest\022\016\n\006" +
      "camera\030\001 \001(\t\"\037\n\016CameraResponse\022\r\n\005frame\030" +
      "\001 \001(\0142F\n\006Camera\022<\n\rCameraService\022\022.sss.C" +
      "ameraRequest\032\023.sss.CameraResponse\"\0000\001B\032\n" +
      "\nsss.CameraB\nCameraImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sss_CameraRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sss_CameraRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sss_CameraRequest_descriptor,
        new java.lang.String[] { "Camera", });
    internal_static_sss_CameraResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sss_CameraResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sss_CameraResponse_descriptor,
        new java.lang.String[] { "Frame", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
