// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Camera.proto

package sss.Camera;

public interface CameraRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sss.CameraRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string camera = 1;</code>
   */
  java.lang.String getCamera();
  /**
   * <code>string camera = 1;</code>
   */
  com.google.protobuf.ByteString
      getCameraBytes();
}
