// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movement.proto

package sss.Movement;

public interface MotionDetectionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sss.MotionDetectionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_moving = 1;</code>
   */
  boolean getIsMoving();
}
