// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movement.proto

package sss.Movement;

public interface MotionDetectionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sss.MotionDetectionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string moving_response = 1;</code>
   */
  java.lang.String getMovingResponse();
  /**
   * <code>string moving_response = 1;</code>
   */
  com.google.protobuf.ByteString
      getMovingResponseBytes();
}
