// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movement.proto

package sss.Movement;

public final class MovementImpl {
  private MovementImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sss_MotionDetectionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sss_MotionDetectionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sss_MotionDetectionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sss_MotionDetectionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sss_RecognitionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sss_RecognitionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sss_RecognitionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sss_RecognitionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Movement.proto\022\003sss\"+\n\026MotionDetection" +
      "Request\022\021\n\tis_moving\030\001 \001(\010\"2\n\027MotionDete" +
      "ctionResponse\022\027\n\017moving_response\030\001 \001(\t\"#" +
      "\n\022RecognitionRequest\022\r\n\005image\030\001 \001(\014\"-\n\023R" +
      "ecognitionResponse\022\026\n\016is_blacklisted\030\001 \001" +
      "(\0102\242\001\n\010Movement\022N\n\017DetectionMotion\022\033.sss" +
      ".MotionDetectionRequest\032\034.sss.MotionDete" +
      "ctionResponse\"\000\022F\n\rRecognizeFace\022\027.sss.R" +
      "ecognitionRequest\032\030.sss.RecognitionRespo" +
      "nse\"\000(\001B\036\n\014sss.MovementB\014MovementImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sss_MotionDetectionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sss_MotionDetectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sss_MotionDetectionRequest_descriptor,
        new java.lang.String[] { "IsMoving", });
    internal_static_sss_MotionDetectionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sss_MotionDetectionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sss_MotionDetectionResponse_descriptor,
        new java.lang.String[] { "MovingResponse", });
    internal_static_sss_RecognitionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sss_RecognitionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sss_RecognitionRequest_descriptor,
        new java.lang.String[] { "Image", });
    internal_static_sss_RecognitionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_sss_RecognitionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sss_RecognitionResponse_descriptor,
        new java.lang.String[] { "IsBlacklisted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
