// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movement.proto

package sss.Movement;

public interface RecognitionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sss.RecognitionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes image = 1;</code>
   */
  com.google.protobuf.ByteString getImage();
}
