// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movement.proto

package sss.Movement;

public interface RecognitionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sss.RecognitionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_blacklisted = 1;</code>
   */
  boolean getIsBlacklisted();
}
