// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageAudio.proto

package sss.MessageAudio;

public interface AudioRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sss.AudioRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes audiosend = 1;</code>
   */
  com.google.protobuf.ByteString getAudiosend();
}
