// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageAudio.proto

package sss.MessageAudio;

public interface AudioResponOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sss.AudioRespon)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes audioreceived = 1;</code>
   */
  com.google.protobuf.ByteString getAudioreceived();
}
