// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageAudio.proto

package sss.MessageAudio;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sss.MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
